### ISSUE TITLE
Realizar a construção da interface

### ISSUE THREAD

**Issue by gusintheeshell** [YanGabriel2022/Your-Climate#3]
Seguir o layout abaixo

![stock-vector-weather-forecast-widget-vector-illustration-daily-weather-forecast-application-template-1835995378](https://user-images.githubusercontent.com/44094756/180300799-0714f123-dc1f-4d10-86e9-62a19cafb6c3.jpg)

Consumir o seguinte endpoint: https://openweathermap.org/forecast5

Algumas observações:
- [x] Layout deve ser responsivo
- [x] O timestamp retornado da api, deve ser tratado da seguinte maneira: dia do mês e mês (ex: 21/07)

**Comment by gusintheeshell** [comment]
![Peek 27-07-2022 18-16](https://user-images.githubusercontent.com/44094756/181374068-bfb62f6f-8bf5-4e48-8cf4-a4a26411a86e.gif)

Dá uma olhada no GRID. Só a mudança que eu fiz ficou no lugar que ela devia ficar. As outras coisas que você fez estão todas desconfiguradas.

**Comment by YanGabrielDev** [comment]
![image](https://user-images.githubusercontent.com/99893016/181496028-8eea65d4-d117-4c7b-b9e4-fd05947b3818.png)
melhorei o grid, agora ele se comporta assim até 600px e os itens ficam alinhados ao centro

**Comment by YanGabrielDev** [comment]
Após 600px os itens agora ocupam cada um com 4 colunas do grid 
![image](https://user-images.githubusercontent.com/99893016/181496934-a3df971f-b0dd-4969-a9f2-9869551e5647.png)
